on: pull_request_review
jobs:
  labelwhenapproved:
    runs_on: ubuntu_latest
    steps:
    - name: label when aprroved
      uses: pullreminders/label-when-approved-action
      env:
        APPROVALS: '1'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
      
